<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KKV864D" failures="2" tests="12" name="Test" time="0.083" errors="0" timestamp="2023-05-31T18:49:49 IST">
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test1" time="0.012">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryfailedTestcase.TestCAse_for_IAnnotation.test1(TestCAse_for_IAnnotation.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryfailedTestcase.TestCAse_for_IAnnotation" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryfailedTestcase.TestCAse_for_IAnnotation.test2(TestCAse_for_IAnnotation.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
